### ISSUE TITLE
Unable to import module 'app': No module named 'flask_lambda'

### ISSUE THREAD

**Issue by kotireddy555** [nikhilkumarsingh/student_api#1]
I was just following your videos. Deployed on aws and getting below error @lamda
Unable to import module 'app': No module named 'flask_lambda'

**Comment by kotireddy555** [comment]
sam build was the problem- it was not building due to python version mismatch

**Comment by lucchesi-rodrigo** [comment]
Hey man! How are you?

How did you solved the problem?

Cheers!
